name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY }}
          external_repository: YoRenChen/YoRenChen.github.io
          publish_dir: docs/.vitepress/dist

      # - name: Deploy
      #   run:
      #     using: docker
      #     image: "Dockerfile"
      #   with:
      #     PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }} # secret 名
      #     PUBLISH_REPOSITORY: YoRenChen/YoRenChen.github.io # 公共仓库，格式：GitHub 用户名/仓库名
      #     BRANCH: master # 分支，填 gh-pages 就行
      #     PUBLISH_DIR: docs/.vitepress/dist # 部署 目录下的文件
